### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by CodeMaxx** [nihal111/MooDLD-for-Android#11]

**Comment by nihal111** [comment]
@CodeMaxx This is urgent.

**Comment by CodeMaxx** [comment]
Net nhi chal rha

**Comment by CodeMaxx** [comment]
What limitations do we want ... the license will depend on that.
https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by CodeMaxx** [comment]
Done
