### ISSUE TITLE
Don't append .pdf to all files

### ISSUE THREAD

**Issue by CodeMaxx** [nihal111/MooDLD-for-Android#12]

**Comment by nihal111** [comment]
What is the solution for this in Python? @CodeMaxx

**Comment by CodeMaxx** [comment]
We extract the letters after the last dot(.) ... There is an array in which
we have the accepted extension... If it is one of those extension then we
download it with that extension.(So basically the extension is stored in a
variable using approx. the last 3 or 4 letters of the download URL - after
removing force download part of-course if its there in the URL)

**Comment by nihal111** [comment]
For main thread links we don't have any extension. "Lecture 1" etc. Are we using the last part in the redirected link for main thread files, in python?  Here,  we are using the link text, what is visible on the website.

**Comment by CodeMaxx** [comment]
So you mean there is no way to get the extensions? That will be a problem

**Comment by nihal111** [comment]
You know what should not be a problem?
Opening github and replying instead of replying from mail

**Comment by CodeMaxx** [comment]
K

## 

Second Year Undergraduate,
Computer Science,
IIT Bombay.
https://codemaxx.github.io/

**Comment by nihal111** [comment]
Fixed .pdf.pdf. Other extensions not incorporated.

**Comment by nihal111** [comment]
Fixed.
