### ISSUE TITLE
Change Download Screen

### ISSUE THREAD

**Issue by nihal111** [nihal111/MooDLD-for-Android#14]
Add a large download button on the main screen. Clicking which would show a filling M with current file progress and download speed(?). The bottom of the screen would then start logging the course names and files being downloaded (like the current log). The log will consist of a list of clickable text views which can be clicked to open the file directly.

**Comment by CodeMaxx** [comment]
Note that the screen should not scroll upwards automatically when the downloaded files are being logged and the order should be reverse chronological i.e. the latest downloaded file at the top of the list.

**Comment by nihal111** [comment]
Either that or we can keep it chronological with auto scroll, hiding the older logs under the download frame.

**Comment by nihal111** [comment]
Done
