### ISSUE TITLE
Download bar becomes negative sometimes

### ISSUE THREAD

**Issue by udiboy1209** [nihal111/MooDLD-for-Android#19]
Observed it the first time I started the app. Will take a screenshot next time.

**Comment by nihal111** [comment]
Do you mean, the circle becomes a whole 360 degree? This is fixed in the latest commit, I think. Or the latest version on PlayStore.

**Comment by udiboy1209** [comment]
I don't know if thats what happened, but it started from like -20% with the arc showing on the other side.

**Comment by nihal111** [comment]
Yeah that was a problem with the library used. The maven version was outdated. It's fixed in the newer version which is imported from jitpack.
