### ISSUE TITLE
[Add UI issues here] User Interface

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/MooDLD-for-Android#7]
There are several points here.
1. On first login, clicking "DLD Files" redirects to "Preferences", and then "Save" redirects back to Main Menu. I am confused what to do next. I am supposed to click "DLD Files" but that is unclear to me. **Suggestion:** Make DLD Files unclickable if Preferences are not set.
2. Replace _save_ with _track_ in "Preferences" because that's what you're doing.
3. What the heck is "DLD Files"? Can't we just call it "My Files"?
4. The root directory it shows me in "Preferences" is _root_/storage/emulated/ but my files are really found in _root_/storage/MooDLD/ What's that about?

**Comment by CodeMaxx** [comment]
Change name to "Update files" and "Download Directory"

**Comment by CodeMaxx** [comment]
Append "MooDLD" to download directory

**Comment by nihal111** [comment]
Suggestion for 1. Send a variable along with the intent on clicking DLD Files, Show a toast in Preferences "You must set your Preferences first." and "Save" should startActivity(DLD_files.class) if that variable is not null.

**Comment by CodeMaxx** [comment]
@nihal111 Rather on the first run, directly Preference page should open

**Comment by nihal111** [comment]
@CodeMaxx I would rather have the DLD files open Preferences. That way I can open Preferences with a toast of "No courses selected" too, even if it's not the first time.

**Comment by nihal111** [comment]
Fixed 4.

**Comment by nihal111** [comment]
In 3. DLD Files is Download Files. And no, we can't call it My Files.
In 2. Aren't we saving preferences?

**Comment by nihal111** [comment]
No 1. is now fixed.
