### ISSUE TITLE
Crashes if Internet is not available

### ISSUE THREAD

**Issue by CodeMaxx** [nihal111/MooDLD-for-Android#9]

**Comment by arpan98** [comment]
Use [this function](https://github.com/arpan98/Eventual-ITSP/blob/android/app/src/main/java/com/nihal/arpan/eventual/EventCreate.java#L391) and add checks at appropriate places.

**Comment by nihal111** [comment]
@arpan98 do this

**Comment by nihal111** [comment]
Fixed
